# 04: Server function ---------------------------------------------------------
# Define server logic required to draw mapPlot and scatterPlot for mainpanel
server <- function(input, output) {
  
  
  # 04a: interactive subset generation ------------------------------------------    
  
  #reactive expression df.sub: generates subset of all datapoints for chosen parameters in app
  df.sub <- reactive({
    
    routelist<- as.vector(NULL)
    
    if (input$routeE == TRUE)
      routelist <- c(routelist, "E") else {NULL} 
    
    if (input$routeW == TRUE)
      routelist <- c(routelist, "W") else {NULL} 
    
    if(input$routeP == TRUE)
      routelist <- c(routelist, "P") else {NULL}
    
    if(input$routeG == TRUE)
      routelist <- c(routelist, "G") else {NULL}
    
    df %>% 
      filter(route %in% routelist &
               date >=input$daterange[1] & date <=input$daterange[2] & 
               Lon >= input$lon_low & Lon <= input$lon_high &
               Lat >=input$lat_low & Lat <= input$lat_high ) %>% 
      dplyr::select(date,Lon,Lat,pCO2,Tem,Sal, cO2,ID)
  })
  
  # reactive expression df.sub.timeseries: generates dataframe to build timeseries plots, means of subset as generated by df.sub
  df.sub.timeseries<-reactive ({
    
    sub.df.timeseries<-df.sub()
    
    sub.df.timeseries %>% 
      group_by(ID) %>% 
      summarise_all(list(~mean(.,na.rm = TRUE),
                         ~min(., na.rm= TRUE),
                         ~max(., na.rm= TRUE),
                         ~sd(., na.rm = TRUE))) %>% 
      dplyr::select(ID,date_mean, pCO2_mean, Tem_mean,Sal_mean,
                    cO2_mean,pCO2_min, pCO2_max, Tem_min, Tem_max,
                    Sal_min, Sal_max, cO2_min, cO2_max,
                    pCO2_sd, Tem_sd, Sal_sd,cO2_sd)
  })
  
  #reactive expression df.sub.hov: generates cut dataframe for hovmoeller plots
  
  df.sub.hov<-reactive({
    
    sub.df.hov<-df.sub()
    
    
    sub.df.hov$dist.trav <- distGeo(cbind(sub.df.hov$Lon, sub.df.hov$Lat), trav) / 1e3
    sub.df.hov$dist.trav.int<-cut(sub.df.hov$dist.trav, seq(0, 1200, 50), labels =
                                    seq(25, 1175, 50))
    sub.df.hov$dist.trav.int<-as.numeric(as.character(sub.df.hov$dist.trav.int))
    
    sub.df.hov$week <- as.Date(cut(sub.df.hov$date, breaks="weeks"))
    
    sub.df.hov<-sub.df.hov %>% 
      dplyr::select(dist.trav.int, week, pCO2, Sal, Tem, cO2)
    
  })
  
  
  #reactive expression df.sub.transect: generates cut dataframe for transect plots
  df.sub.transect<-reactive({
    
    routelist<- as.vector(NULL)
    
    if (input$routeE == TRUE)
      routelist <- c(routelist, "E") else {NULL} 
    
    if (input$routeW == TRUE)
      routelist <- c(routelist, "W") else {NULL} 
    
    if(input$routeP == TRUE)
      routelist <- c(routelist, "P") else {NULL}
    
    if(input$routeG == TRUE)
      routelist <- c(routelist, "G") else {NULL}
    
    df %>% 
      filter(route %in% routelist &
               date >=input$daterange[1] & date <=(input$daterange[1]+14) & 
               Lon >= input$lon_low & Lon <= input$lon_high &
               Lat >=input$lat_low & Lat <= input$lat_high ) %>% 
      dplyr::select(date,Lon,Lat,pCO2,Tem,Sal, cO2,ID)
    
  })
  
  df.sub.transect2<-reactive({
    
    sub.df.transect<-df.sub.transect()
    
    sub.df.transect$dist.trav<-distGeo(cbind(sub.df.transect$Lon, sub.df.transect$Lat), trav)/1e3
    
    sub.df.transect$date<-as.character(lubridate::ymd(sub.df.transect$ID))
    sub.df.transect<-sub.df.transect %>% 
      arrange(desc(date))
    
  })
  # 04a: Output Values per point ------------------------------------------------  
  output$ValuesPerPoint <- renderText({
    
    sub.df.timeseries.data<-df.sub.timeseries()   #means
    sub.df<-df.sub()                              #all observations
    
    paste("One datapoint represents one crossing of the ferry 'Finnmaid'. Data gets collected every minute. Depending on your selection a different number of measurments are averaged to represent the crossing.
          The mean number of values per datapoint for your selection is", round((nrow(sub.df)/nrow(sub.df.timeseries.data))), ".")
  })
  # 04b: Output Map Plot ------------------------------------------------ 
  
  output$mapPlot <- renderPlot({
    p<-ggplot() +
      coord_quickmap(xlim=c(xmin, xmax), ylim=c(ymin, ymax)) +
      geom_polygon(data=basemap, aes(x=long, y=lat, group=group), fill=land.colour, colour = border.colour, lwd=.5)+
      geom_rect(data=data.frame(), 
                mapping = aes(xmin= input$lon_low, xmax = input$lon_high, 
                              ymin=input$lat_low, ymax= input$lat_high), 
                alpha = 0.2, col="black")+
      labs(x="Longitude [deg E]", y="Latitude [deg N]", size = 2)+
      theme_minimal()+
      scale_color_brewer(palette = "Set1", name="Example Routes")
    
    if (input$routeE == TRUE)
      (p<-p+
         geom_path(data= routeE,aes(x= routeE$Lon, y= routeE$Lat, colour = "E"))) else  {NULL}
    
    if (input$routeW == TRUE)
      (p<-p +
         geom_path(data= routeW,aes(x= routeW$Lon, y= routeW$Lat, colour="W"))) else
         {NULL}
    if (input$routeG == TRUE)
      (p<-p +
         geom_path(data= routeG,aes(x= routeG$Lon, y= routeG$Lat, colour = "G"))) else
         {NULL}
    if (input$routeP == TRUE)
      (p<- p+
         geom_path(data= routeP,aes(x= routeP$Lon, y= routeP$Lat, colour = "P"))) else
         {NULL}
    p
    
  })
  # 04b: Output Checkbox Plots ------------------------------------------------
  # 04b1: Axis Labels ------------------------------------------------
  ## information for axis titles
  a <- list(title = "Date",
            showticklabels = TRUE)
  b<- list (
    title = "pCO2 [ppm]",
    showticklabels = TRUE)
  g<- list(
    title = "Temperature [deg C]",
    showticklabels = TRUE)
  d<- list(
    title = "Salinity",
    showticklabels = TRUE)
  e<-list(
    title = "CH4",
    showticklabels = TRUE)
  f<- list(
    title= "O2 [umol L-1]",
    showticklabels = TRUE)
  h<-list("Distance to Travemuende [km]", showticklabels = TRUE)
  # 04b2: Time Series Plots -----------------------------------------------
  output$plot_timeseries <- renderPlotly({
    
    plotlist<- NULL
    sub.df.timeseries.data<-df.sub.timeseries()
    
    ### PLOT MEAN pCO2 ###
    
    p1<-plot_ly(sub.df.timeseries.data, name = "Mean pCO2", showlegend = FALSE) %>% #, height = (400*(length(plotlist))), width = 800) %>% 
      add_trace(x= ~sub.df.timeseries.data$date_mean, y= ~sub.df.timeseries.data$pCO2_mean,type= 'scatter', 
                mode= 'markers', marker = list(symbol= "circle", size=4, color="grey"), 
                #error_y= ~list(type = "data", array=df.sub$pCO2_sd, color= "grey"), 
                hoverinfo = 'text',
                text = ~paste('</br> Mean pCO2',
                              '</br> Date:', sub.df.timeseries.data$date_mean,
                              '</br> Mean: ',  round(sub.df.timeseries.data$pCO2_mean, digits= 2) ,
                              '</br> Max: ', round(sub.df.timeseries.data$pCO2_max, digits = 2),
                              '</br> Min: ', round(sub.df.timeseries.data$pCO2_min, digits = 2))) %>% 
      layout( xaxis= a, yaxis = b) 
    
    ### PLOT MEAN Temperature ###
    
    p2<-plot_ly(sub.df.timeseries.data, name = "Mean Temperature", showlegend = FALSE, height = (400*4),  width = 1200) %>%
      
      add_trace(x= ~sub.df.timeseries.data$date_mean, y= ~sub.df.timeseries.data$Tem_mean,type= 'scatter',
                mode= 'markers', marker = list(symbol= "circle", size=4, color="grey"),
                #error_y= ~list(type = "data", array=df.sub$Tem_sd,color= "grey"),
                hoverinfo = 'text',
                text = ~paste('</br> Mean Temp',
                              '</br> Date', sub.df.timeseries.data$date_mean,
                              '</br> Mean: ',  round(sub.df.timeseries.data$Tem_mean, digits= 2) ,
                              '</br> Max: ', round(sub.df.timeseries.data$Tem_max, digits = 2),
                              '</br> Min: ', round(sub.df.timeseries.data$Tem_min, digits = 2))) %>%
      layout(xaxis = a, yaxis = g, autosize = FALSE)
    
    
    ### PLOT MEAN SALINITY ###
    p3<- plot_ly(sub.df.timeseries.data, name = "Mean Salinity", showlegend = FALSE,height = (400*4), width = 1200) %>%
      add_trace(x= ~ sub.df.timeseries.data$date_mean, y= ~ sub.df.timeseries.data$Sal_mean,type= 'scatter',
                mode= 'markers', marker = list(symbol= "circle", size=4, color="grey"),
                #error_y= ~list(type = "data", array=sub.df.timeseries.data$Sal_sd,color= "grey"),
                hoverinfo = 'text',
                text = ~paste('</br> Mean Sal',
                              '</br> Date', sub.df.timeseries.data$date_mean,
                              '</br> Mean: ',  round(sub.df.timeseries.data$Sal_mean, digits= 2) ,
                              '</br> Max: ', round(sub.df.timeseries.data$Sal_max, digits = 2),
                              '</br> Min: ', round(sub.df.timeseries.data$Sal_min, digits = 2))) %>%
      layout(xaxis= a, yaxis = d,  autosize= FALSE)
    
    
    ### PLOT MEAN CH4 ###
    
    # add when data is available
    
    ### PLOT MEAN O2
    
    p5<- plot_ly(sub.df.timeseries.data, name = "Mean O2", showlegend = FALSE,height = (400*4),  width = 1200) %>%
      add_trace(x= sub.df.timeseries.data$date_mean, y= sub.df.timeseries.data$cO2_mean,type= 'scatter',
                mode= 'markers', marker = list(symbol= "circle", size=4, color="grey"),
                #error_y= ~list(type = "data", array=sub.df.timeseries.data$cO2_sd, color= "grey"),
                hoverinfo = 'text',
                text = ~paste('</br> Mean O2',
                              '</br> Date', sub.df.timeseries.data$date_mean,
                              '</br> Mean: ',  round(sub.df.timeseries.data$cO2_mean, digits= 2) ,
                              '</br> Max: ', round(sub.df.timeseries.data$cO2_max, digits = 2),
                              '</br> Min: ', round(sub.df.timeseries.data$cO2_min, digits = 2))) %>%
      layout(xaxis= a, yaxis = f,  autosize= FALSE)
    
    
    plotlist<-list(p1,p2,p3,p5)
    
    subplot(plotlist, nrows= length(plotlist), shareX = TRUE, titleY = TRUE)
  })
  
  # 04d: Hovmoeller Plots ------------------------------------
  #Hovmoeller Plot pCO2 Mean
  
  output$hov_pCO2_mean <- renderPlot({
    
    sub.df.hov.data<-df.sub.hov()
    
    sub.df.hov.data<-sub.df.hov.data %>% 
      dplyr::group_by(dist.trav.int, week) %>% 
      summarise_all(list(mean=~mean(.,na.rm=TRUE))) %>% 
      as.data.frame() 
    
    sub.df.hov.data$dist.trav.int<-as.numeric(as.character(sub.df.hov.data$dist.trav.int))
    sub.df.hov.data$week<-as.POSIXct(sub.df.hov.data$week)
    
    hov1 <-
      sub.df.hov.data %>% 
      filter(!is.na(pCO2_mean)) %>% 
      ggplot()+
      geom_raster(aes(week, dist.trav.int, fill= pCO2_mean))+
      scale_fill_viridis_c(name="pCO2 [ppm]", direction = -1)+
      geom_vline(xintercept = as.numeric(seq(as.POSIXct("2003/1/1", tz="GMT"), 
                                             as.POSIXct("2018/1/1", tz="GMT"), 
                                             "years")),
                 size=1)+
      scale_x_datetime(expand = c(0,0))+
      scale_y_continuous(expand = c(0,0))+
      labs(y="Distance to Travemuende [km]")+
      theme_bw()+
      theme(
        axis.title.x = element_blank(),
        legend.position = "bottom",
        legend.key.width = unit(1.3, "cm"),
        legend.key.height = unit(0.3, "cm")
      )
    
    hov1
    
  })
  #Hovmoeller Plot Temperatur Mean
  output$hov_temp_mean <- renderPlot({
    
    sub.df.hov.data<-df.sub.hov()
    
    sub.df.hov.data<- sub.df.hov.data %>% 
      dplyr::group_by(dist.trav.int, week) %>% 
      summarise_all(list(mean=~mean(.,na.rm=TRUE))) %>% 
      as.data.frame() 
    
    sub.df.hov.data$dist.trav.int<-as.numeric(as.character( sub.df.hov.data$dist.trav.int))
    sub.df.hov.data$week<-as.POSIXct( sub.df.hov.data$week)
    
    hov2 <-sub.df.hov.data %>% 
      filter(!is.na(Tem_mean)) %>%
      ggplot()+
      geom_raster(aes(week, dist.trav.int, fill= Tem_mean))+ 
      scale_fill_viridis_c(option= "plasma", name="Temperature [deg C]", direction = 1)+
      geom_vline(xintercept = as.numeric(seq(as.POSIXct("2003/1/1", tz="GMT"), 
                                             as.POSIXct("2018/1/1", tz="GMT"), 
                                             "years")),
                 size=1)+
      scale_x_datetime(expand = c(0,0))+
      scale_y_continuous(expand = c(0,0))+
      labs(y="Distance to Travemuende [km]")+
      theme_bw()+
      theme(
        axis.title.x = element_blank(),
        legend.position = "bottom",
        legend.key.width = unit(1.3, "cm"),
        legend.key.height = unit(0.3, "cm")
      )
    hov2
  })
  
  
  #Hovmoeller Plot Salinity Mean
  output$hov_sal_mean <- renderPlot({
    
    
    sub.df.hov.data<-df.sub.hov()
    
    sub.df.hov.data<- sub.df.hov.data %>% 
      dplyr::group_by(dist.trav.int, week) %>% 
      summarise_all(list(mean=~mean(.,na.rm=TRUE))) %>% 
      as.data.frame() 
    
    sub.df.hov.data$dist.trav.int<-as.numeric(as.character( sub.df.hov.data$dist.trav.int))
    sub.df.hov.data$week<-as.POSIXct( sub.df.hov.data$week)
    
    hov3 <-sub.df.hov.data %>% 
      filter(!is.na(Sal_mean)) %>%
      ggplot()+
      geom_raster(aes(week, dist.trav.int, fill= Sal_mean))+ 
      scale_fill_viridis_c(option= "cividis",name="Salinity", direction = 1)+
      geom_vline(xintercept = as.numeric(seq(as.POSIXct("2003/1/1", tz="GMT"), 
                                             as.POSIXct("2018/1/1", tz="GMT"), 
                                             "years")),
                 size=1)+
      scale_x_datetime(expand = c(0,0))+
      scale_y_continuous(expand = c(0,0))+
      labs(y="Distance to Travemuende [km]")+
      theme_bw()+
      theme(
        axis.title.x = element_blank(),
        legend.position = "bottom",
        legend.key.width = unit(1.3, "cm"),
        legend.key.height = unit(0.3, "cm")
      )
    hov3
  })
  
  #Hovmoeller Plot CH4 Mean
  
  
  #Hovmoeller Plot O2
  output$hov_o2_mean <- renderPlot({
    
    sub.df.hov.data<-df.sub.hov()
    
    sub.df.hov.data<-sub.df.hov.data %>% 
      dplyr::group_by(dist.trav.int, week) %>% 
      summarise_all(list(mean=~mean(.,na.rm=TRUE))) %>% 
      as.data.frame() 
    
    sub.df.hov.data$dist.trav.int<-as.numeric(as.character(sub.df.hov.data$dist.trav.int))
    sub.df.hov.data$week<-as.POSIXct(sub.df.hov.data$week)
    
    hov4 <-sub.df.hov.data %>% 
      filter(!is.na(cO2_mean)) %>%
      ggplot()+
      geom_raster(aes(week, dist.trav.int, fill= cO2_mean))+ #changed here: fill = Tem_mean to mean
      scale_fill_viridis_c(option= "cividis", name="cO2 [umol L-1]", direction = 1)+
      geom_vline(xintercept = as.numeric(seq(as.POSIXct("2003/1/1", tz="GMT"), 
                                             as.POSIXct("2018/1/1", tz="GMT"), 
                                             "years")),
                 size=1)+
      scale_x_datetime(expand = c(0,0))+
      scale_y_continuous(expand = c(0,0))+
      labs(y="Distance to Travemuende [km]")+
      theme_bw()+
      theme(
        axis.title.x = element_blank(),
        legend.position = "bottom",
        legend.key.width = unit(1.3, "cm"),
        legend.key.height = unit(0.3, "cm")
      )
    hov4
  }) 
  
  # 04e: Transect Plots -------------------------------------------------- 
  
  ### Transect Plot pCO2 ###
  
  output$plot_transect <- renderPlotly({
    
    plotlist<-NULL
    sub.df.transect<-df.sub.transect2()
    
    #IDEA: instead of error "Subscript out of bounce" a message is to be displayed stating the actual problem
    #that there are no IDs in the 14 days after start, and anothe startdate has to be picked, not working though
    validate(
      need(sub.df.transect$ID, "No data in a 14 days window after the start date, please choose a different start date")
    )
    
    # Transectplot pCO2
    
    t1<-sub.df.transect %>%
      group_by(date) %>% 
      ggplot(aes(x= dist.trav, y= pCO2, color = ID), height = 400,  width = 1200)+
      geom_line()+
      scale_color_viridis_d(direction = -1)+
      ylab("pCO2 [ppm]")+
      xlab("Distance to Travemuende [km]")+
      theme_bw()+
      theme(legend.position = "none")
    
    #Transectplot Temperature
    t2<-sub.df.transect %>% 
      group_by(date) %>% 
      ggplot(aes(x= dist.trav, y= Tem, color = ID), height = 400,  width = 1200)+
      geom_line()+
      scale_color_viridis_d(direction = -1)+
      ylab("Temperature [deg C]")+
      xlab("Distance to Travemuende [km]")+
      theme_bw()+
      theme(legend.position = "none")
    
    #Transectplot Salinity
    t3<-sub.df.transect %>% 
      group_by(date) %>% 
      ggplot(aes(x= dist.trav, y= Sal, color = ID), height = 400,  width = 1200)+
      geom_line()+
      scale_color_viridis_d(direction = -1)+
      ylab("Salinity")+
      xlab("Distance to Travemuende [km]")+
      theme_bw()+
      theme(legend.position = "none")
    
    #Transectplot O2
    t5<-sub.df.transect %>% 
      group_by(date) %>% 
      ggplot(aes(x= dist.trav, y= cO2, color = ID), height = 400,  width = 1200)+
      geom_line()+
      scale_color_viridis_d(direction = -1)+
      ylab("O2[umol L-1]")+
      xlab("Distance to Travemuende [km]")+
      theme_bw()+
      theme(legend.position = "none")
    
    #Plotlist and creation of Subplot    
    plotlist<-list(t1,t2,t3,t5)
    
    subplot(plotlist, nrows= length(plotlist), shareX = TRUE, titleY = TRUE)
  })
  
  # 04f: download CSV ------------------------------------------------
  #https://shiny.rstudio.com/articles/download.html  
  
  datasetInput <- reactive({
    
    sub.df.hov.data<-df.sub.hov()
    sub.df.hov.data<-sub.df.hov.data %>% 
      dplyr::group_by(dist.trav.int, week) %>% 
      summarise_all(list(mean=~mean(.,na.rm=TRUE))) %>% 
      as.data.frame() 
    
    sub.df.hov.data$dist.trav.int<-as.numeric(as.character(sub.df.hov.data$dist.trav.int))
    sub.df.hov.data$week<-as.POSIXct(sub.df.hov.data$week)
    
    switch(input$dataset,
           "Time Series Data" = df.sub.timeseries(),
           
           "Transect Data" = df.sub.transect2(),
           
           "Hovmoeller Data" = sub.df.hov.data
    )
  })
  
  output$downloadData <- downloadHandler(
    filename = function(){
      paste(input$dataset,"_",input$daterange[1],"-", input$daterange[2],"_lon", 
            input$lon_low,"-", input$lon_high,"_lat", input$lat_low ,"-",
            input$lat_high , ".csv", sep = "")
    },
    content = function(file){
      write.csv(datasetInput(), file, row.names = FALSE)
    }
  )
  } #end server function